### ISSUE TITLE
.opendb, .db 등 commit 문제

### ISSUE THREAD

**Issue by younghovpak** [mingz17/OpenSW_Team2_StudentManagement#11]
## .opendb, .db 등 commit 문제

* .opendb, .db 등 파일을 gitignore에 추가해도 계속해서 untracked 된 파일이 있다는 문제가 있어 commit에 큰 불편함을 겪고 있습니다.
* 해당 문제에 대한 해결 방법을 알고 있는 분은 답글 남겨주시면 감사하겠습니다!

**Comment by cj1ne** [comment]
#12

**Comment by younghovpak** [comment]
@cj1ne Just saw this. Thank you for your kindness. It works well now.
