### ISSUE TITLE
공지사항 등록 에러

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#18]
### Context
Notice Management에서 공지사항을 등록하는 기능이 정상적으로 작동하지 않습니다.

### Current Result
There is no lecture on Tuesday라고 등록을 하고나서 Print 기능을 통해 출력을 하면 There만 출력이 됩니다.

### Expected result
정상적으로 작동된다면 Print 기능을 실행했을 때, There is no lecture on Tuesday 전부가 출력되야 할 것 같습니다.

### Additional info
현재 코드에서 There is no lecture on Tuesday를 등록하고나서 출력한 화면입니다.
![default](https://user-images.githubusercontent.com/26850169/40066711-b094d968-589f-11e8-99f1-e33b7d57ad3f.PNG)

**Comment by Haeeeun** [comment]
앗 확인해보겠습니다!

**Comment by cj1ne** [comment]
#21
