### ISSUE TITLE
Issue template 미적용 상태

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#19]
### Context
Issue template을 Custom.md라는 파일을 추가해서 올리신 것 같은데 적용이 되지 않습니다.

### Current Result
Issue를 작성할 때마다 사용자가 양식에 맞출 수 있도록 Issue template이 정상적으로 적용되어야 하는데 빈 화면이 나타납니다.

### Expected result
Issue를 작성할 때마다 사용자가 양식에 맞출 수 있도록 항목이 있고, 항목마다 어떻게 작성해야하는지에 대한 설명이 출력되어야할 것 같습니다. 현재 issue template은 Custom.md 파일에 있는 내용을 복사하여 기재한 것입니다.

### Additional info
제 생각에는 Custom.md가 README나 LICENSE등과 달리 특정 디렉토리 안에 있는 것이 문제인 것 같은데, 이 부분을 담당하신 분께서는 수정해서 올려주시면 감사하겠습니다,

**Comment by Haeeeun** [comment]
넵 이슈탬플릿을 develop에 올렸었는데 master에 올려보겠습니다!

**Comment by Haeeeun** [comment]
![default](https://user-images.githubusercontent.com/26876591/40191242-d2277d4a-5a3b-11e8-917c-44818e65a333.JPG)

Isuue template을 master브랜치에 올렸더니 해결되었습니다~

**Comment by cj1ne** [comment]
감사합니다!
