### ISSUE TITLE
변수studentNumber 에 대해

### ISSUE THREAD

**Issue by mingz17** [mingz17/OpenSW_Team2_StudentManagement#25]
### Context
구조체 Course에서 선언된 변수studentNumber의 이름이 변경되어야 할 것 같습니다.
studentCount나 다른 이름으로 수정하려는데 어떻게 생각하시나요?

### Current Result
각 과목당 학생 수를 뜻하고 있는 studentNumber는 
학생 번호로 착각할 수 있는 등 의미적 혼동을 줄 수 있다고 생각합니다.

### Expected result
 수정한다면 코드를 처음 보는 사람들도 변수의 의미를 명확하게 알 수 있게 될 것입니다. 

### Additional info
*Please add any information of interest here below*

**Comment by sssukho** [comment]
studentCount 변수 주석에 무엇을 의미하는지도 같이 적어주시면 헷갈리지 않고 좋을 것 같습니다!

**Comment by cj1ne** [comment]
맞아요 학번과 혼동되서 저도 학생 구조체의 학번 변수명을 우선 id로 변경했거든요! 전studentCount 괜찮은 것 같습니다!

**Comment by cj1ne** [comment]
#43
