### ISSUE TITLE
Assignment delete function bug

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#27]
### Context
*Please explain here below what you were doing when the issue happened*
Assignment delete function show the list of assignment at first. If I choose the right index of list, It works well. But If I input wrong index, it constantly prints "success".

### Current Result
*Please describe here below the current result you got*
![default](https://user-images.githubusercontent.com/26850169/40324694-3b31fbb8-5d74-11e8-9308-a52eef3aa3d6.PNG)

### Expected result
*Please describe here below what should be the expected behaviour*
I think that assignment delete function should print "success" only when the assignment is deleted. And I think that it would be better to show the existing assignment list, not including empty assignment components.

### Additional info
*Please add any information of interest here below*

**Comment by younghovpak** [comment]
@cj1ne Thank you Jongwon for your feedback. It will be fixed very soon.

**Comment by younghovpak** [comment]
@cj1ne Fixed the exception and opened pr right before. #48
