### ISSUE TITLE
Notice modify function exception

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#28]
### Context
When I want to modify notice list, notice function show the list of notice. And If I input number which is out of index of list, the function prints "success"

### Current Result
![default](https://user-images.githubusercontent.com/26850169/40325159-b8dfeefc-5d75-11e8-80ce-909d1a714574.PNG)

### Expected result
Showing list of notice that is registered is good. But I think that it would be better to say like this "Modify function was not working because notice of that index doesn't exist." If you solve this problem, please pull request!

**Comment by Haeeeun** [comment]
그 부분은 생각을 못했네요 수정함수뿐만아니라 삭제함수에도 이 문제가 있는지 확인후 수정해서 다시 pull request에 올리겠습니다!
