### ISSUE TITLE
PrintStudent function bug

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#29]
### Context
*Please explain here below what you were doing when the issue happened*
PrintStudent function is working irrelevantly. Showing the list of student is worked well, but the format is not working.

### Current Result
*Please describe here below the current result you got*
![image](https://user-images.githubusercontent.com/26850169/40326398-0ae64ae4-5d7a-11e8-9f02-1ebe978cd5ff.png)

### Expected result
*Please describe here below what should be the expected behaviour*
"?????????????????????????????" this part should be removed or modified. 

### Additional info
*Please add any information of interest here below*
 I think that this problem would be related to #26. After fixing this part, check #26 issue and pull request together please.

**Comment by mingz17** [comment]
특수문자 때문에 이상해진 것 같네요
수정해서 pull request 올리겠습니다!
