### ISSUE TITLE
학생 구조체 배열에 대해서

### ISSUE THREAD

**Issue by mingz17** [mingz17/OpenSW_Team2_StudentManagement#3]
지금은 학생을 정해진 크기의 배열로 선언했지만,
과목을 추가하고 출력하는 등의 기능을 수행하기 위해서는 불편함이 있다고 생각합니다.
배열을 동적할당으로 바꾸고 함수들의 매개변수도 변경하면서 
전체적으로 수정이 필요할 것 같은데 어떻게 생각하시나요?

**Comment by sssukho** [comment]
음 저도 학생이 몇명인지도 모르는데 그렇게 사이즈가 정해져있다는게 살짝 마음에 안들었습니다!
동적배열로 바꾸는게 나을 것 같아요!

**Comment by cj1ne** [comment]
제가 수정해서 pull request해볼게요!

**Comment by cj1ne** [comment]
제가 전반적으로 수정해서 pull request에 올려볼게요 !
