### ISSUE TITLE
ReadFile 함수와 txt파일

### ISSUE THREAD

**Issue by mingz17** [mingz17/OpenSW_Team2_StudentManagement#30]
### Context
원격 develop도 확인해봤는데
sample_course.txt가 아니라 student.txt로 되어 있어서 파일을 읽지 못하고 있습니다.
그런데도 ReadFile을 실행했을 때 아래 스크린샷처럼,
'Cannot open the file' 이 출력되지 않고 'File data is successfully loaded!' 가 출력됩니다.

### Current Result
![image](https://user-images.githubusercontent.com/34908753/40344490-fbf16518-5dcf-11e8-9b85-dd9d0a02b836.png)

### Expected result
*Please describe here below what should be the expected behaviour*

### Additional info
*Please add any information of interest here below*

**Comment by cj1ne** [comment]
I think that this part is related to @younghovpak . If you checked this, please comment, fix and pull request.

**Comment by sssukho** [comment]
@cj1ne It was belong to me bro. I'm gonna fix it and write a pull request soon. :)
