### ISSUE TITLE
한국어 인코딩으로 로드하는 동안 일부 바이트가 유니코드 대체 문자로 바뀌었습니다.

### ISSUE THREAD

**Issue by younghovpak** [mingz17/OpenSW_Team2_StudentManagement#32]
### Context
* There is an error message below when solution starts. It looks like Minji @mingz17 experienced before. Do you guys know the solutions about this error?
```
한국어 인코딩으로 로드하는 동안 일부 바이트가 유니코드 대체 문자로 바뀌었습니다.
```

### Current Result
![unicode-error](https://user-images.githubusercontent.com/26853043/40352828-e13948ce-5dea-11e8-9aa1-5fc0ae479d68.PNG)

**Comment by mingz17** [comment]
아마 주석을 달기 위해서 썼던 한글이 로딩하면서 유니코드 대체문자로 바뀐 것 같습니다.
저는 그냥 실행해도 주석에 한글이 좀 깨질 뿐이어서, 그냥 영어로 주석을 달아 에러를 없앴습니다.

에러에 대해 찾아보니 visual 프로그램에서 
[도구] - [옵션] - [텍스트 편집기] - [일반] - "서명 없는 UTF-8 인코딩 자동 검색(D)" 체크 해제
![image](https://user-images.githubusercontent.com/34908753/40416043-4af67a58-5eb7-11e8-955e-45f99ce56a84.png)
이렇게 하셔도 에러가 사라지는 것 같습니다!

**Comment by younghovpak** [comment]
@mingz17 Just saw this. Thank your for your advice. It works well.
