### ISSUE TITLE
함수명 통일

### ISSUE THREAD

**Issue by younghovpak** [mingz17/OpenSW_Team2_StudentManagement#33]
### Context
* 현재 함수명이 어떤 함수는 첫 글자가 소문자이고 어떤 함수는 첫 글자가 대문자더라고요. 함수명을 통일하면 좋을 거 같습니다. 아래 스크린샷 이미지가 하나의 예입니다!

### Current Result
![function_naming_convention](https://user-images.githubusercontent.com/26853043/40353820-685159bc-5ded-11e8-8cc0-c39cc643b781.PNG)

**Comment by sssukho** [comment]
스크린샷에는 첫글자가 소문자로 되어있는데 그럼 소문자로 시작하는 함수명으로 통일을 하면되는건가요?

**Comment by cj1ne** [comment]
Yes, I checked it. This part is too small to do pull request. So I reflected it when I did pull request. Please check changed code in #46 .
