### ISSUE TITLE
전체적인 User Interface 변경 요청

### ISSUE THREAD

**Issue by younghovpak** [mingz17/OpenSW_Team2_StudentManagement#34]
### Context
* 현재 UI가 너무 단조롭다는 개인적인 생각이 있습니다. 조금 더 정렬된 화면으로 바뀌면 더 좋을 거 같습니다!

### Current Result
![studentmanagement_ui](https://user-images.githubusercontent.com/26853043/40354030-e4d08bca-5ded-11e8-8103-bb6f3d7e8228.PNG)

**Comment by mingz17** [comment]
네 저도 그렇게 생각해요!
만나서 UI에 대해 상의해보고 수정하는게 나을 것 같습니다

**Comment by Haeeeun** [comment]
저도 그렇게 생각합니다!

**Comment by cj1ne** [comment]
네네 저희 방금 스카이프로 UI상의한대로, @younghovpak 이 정리해서 수정 후에 PR해주시면 검토 후에 바로 적용하도록해요!
