### ISSUE TITLE
과목 등록 오류

### ISSUE THREAD

**Issue by Haeeeun** [mingz17/OpenSW_Team2_StudentManagement#35]
### Current Result
과목을 등록후 수정이나 삭제,관리메뉴에 들어갔다가 다시 과목을 등록하려 1번을 누르면
빈 값이 과목 이름으로 등록되어 버립니다

### Expected result
다른메뉴에 들어갔다가 나와도 정상적으로 과목이 등록될 수 있도록 해야할 거 같습니다

### Additional info
![5](https://user-images.githubusercontent.com/26876591/40354580-2a071f96-5def-11e8-8bcc-1b983a42a21a.JPG)
![4](https://user-images.githubusercontent.com/26876591/40354579-29d95110-5def-11e8-84d9-9a8a30a2e1ea.JPG)

**Comment by mingz17** [comment]
메뉴 선택 후 enter를 누르셔서 바로 엔터값이 입력된 것 같은데 
다시 한 번 확인 해봐주실 수 있나요?

**Comment by Haeeeun** [comment]
아 다시 한번 확인해 봤는데 메뉴 선택 후 enter를 누르긴합니다 근데
![9](https://user-images.githubusercontent.com/26876591/40355276-f1e271c2-5df0-11e8-8282-9aa742eac1c5.JPG)
이 상황에선 0을 누르고 enter를 눌러야 다음 기능으로 넘어갈 수 있어서 누를수밖에 없는거 같은데..
메뉴 선택 후 엔터값이 입력되더라도 빈값이 입력되지 않도록 할 수는 없을까요?

**Comment by cj1ne** [comment]
I checked it. I think that it was caused by scanf. So I'll add getchar() to get the enter key after using scanf.
