### ISSUE TITLE
과제 수정, 삭제함수에서 필요없는 문장 출력

### ISSUE THREAD

**Issue by Haeeeun** [mingz17/OpenSW_Team2_StudentManagement#36]
### Current Result
과제 수정이나 삭제함수에서 3초후에 메뉴화면으로 돌아가지 않음에도 it will return to assignment menu 3 seconds later 라는 문장이 나옵니다

### Additional info
![6](https://user-images.githubusercontent.com/26876591/40355940-b49bd86a-5df2-11e8-801a-06b3090c9384.JPG)

**Comment by younghovpak** [comment]
@Haeeeun Thanks for your feedback. It will be fixed very soon.

**Comment by younghovpak** [comment]
#48 Fixed the exception and opened pull request right before. @Haeeeun
