### ISSUE TITLE
WriteScoreFile 함수

### ISSUE THREAD

**Issue by Haeeeun** [mingz17/OpenSW_Team2_StudentManagement#37]
### Current Result
코드 중에 WriteScoreFile() 함수가 비어있습니다. 헤더파일에도 선언되어 있지 않은 함수던데 혹시 앞으로 구현할 예정인 함수인가요?

### Additional info
![8](https://user-images.githubusercontent.com/26876591/40356253-7c1f9e76-5df3-11e8-948a-cda0b3186d1b.JPG)

**Comment by cj1ne** [comment]
저희가 처음에 개발 계획할 때에는 과목의 학생, 성적을 나누어서 파일 입출력 기능을 하게 할까 했는데, 저번에 회의 때 말씀드렸다싶이 메인 관리창에서 과목의 모든 정보를 입출력하도록 변경하였습니다. 그래서 ScoreManagement, StudentManagment의 파일 입출력 함수가 없어지고 ReadFile, WriteFile함수 하나씩 있어야하는데 저 부분을 지운다는 것을 깜빡했나 봅니다! 수정하도록 하겠습니다 :)
