### ISSUE TITLE
gets function modifying

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#38]
### Context
Most of us used gets() function to get the string which include space from user. But I heard that gets function is not stable and dangerous for input function. Because it doesn't have limitation of input. So I think that it would be better to use fgets function than gets function.

### Current Result
If I input more than size of input array, the program is ended.
![image](https://user-images.githubusercontent.com/26850169/40361652-0a0dda70-5e05-11e8-988a-6b36e585283b.png)

### Expected result
If we changed gets function to fgets function, the program will only use size of input array when the input size is longer than array size. It means that program will not be ended. 

### Additional info
The example of using fgets function is like this : fgets(courseName, sizeof(courseName), stdin). First parameter is the variable where the input will be stored, the second parameter is the limitation of input, and the last parameter means we will get the string from user's input.

And the result of fgets function will include '\n' at the last. So we should change it to '\0'.
For example, str[strlen(str)-1] = '\0'

**Comment by mingz17** [comment]
제가 맡은 부분에서 gets()가 쓰인 부분 확인하고 수정하겠습니다!

**Comment by Haeeeun** [comment]
저도 입력받는 부분에 gets 함수를 썼었는데 안정적이지 않다는것을 몰랐네요 추천해주신 fgets 함수로 수정해보겠습니다!

**Comment by cj1ne** [comment]
I changed all of gets function to fgets function in program. So you don't need to change it. Just check it in #46 !
