### ISSUE TITLE
과목을 등록하지 않은 상태에서 바로 Manage 메뉴로 들어갈 수 있는 오류

### ISSUE THREAD

**Issue by sssukho** [mingz17/OpenSW_Team2_StudentManagement#39]
### Context
가장 초기화면에서 4번(Manage)로 들어간 후, 등록된 과목이 출력이 되어야 하는데 아무런 글자만 치면
과목 관리 메뉴로 넘어갈 수 있습니다.

### Current Result
![image](https://user-images.githubusercontent.com/28735418/40364474-60c4fcf6-5e0d-11e8-828a-fdf35963be18.png)

![image](https://user-images.githubusercontent.com/28735418/40364486-69364aac-5e0d-11e8-91ad-36382c683df5.png)

### Expected result
초기화면에서 과목이 등록이 되지 않은 상태에서 4번을 입력하면 에러 메시지와 함께 다시 초기화면으로
돌아가게끔 예외처리를 해야할 것 같습니다.

**Comment by cj1ne** [comment]
네, 저도 저 부분을 수정하려 했었는데 미처 하지 못했습니다 :( 예외처리해서 PR후 해당 PR을 코멘트로 올리겠습니다!

**Comment by cj1ne** [comment]
#46 Please join here. @sssukho
