### ISSUE TITLE
Visual Studio 빌드시 stdio.h 없다는 오류

### ISSUE THREAD

**Issue by younghovpak** [mingz17/OpenSW_Team2_StudentManagement#4]
![stdio-error](https://user-images.githubusercontent.com/26853043/39910983-9aa1e3c6-5534-11e8-959f-5507abb9dc57.PNG)

* 이전에 발생하지 않았던 오류인데 Visual Studio로 빌드시 위 사진과 같이 stdio.h, string.h가 없다는 오류가 나타납니다.
* 해당 이슈에 대해 해결 방법을 알고 계시면 답변 달아주시면 감사하겠습니다!

**Comment by sssukho** [comment]
### Visual Studio 빌드시 stdio.h 없다는 오류에 대한 해결 방법

* 해당 오류는 Windows 10에서 C 런타임용 라이브러리가 Visual Studio 폴더를 벗어나 리팩토링 되었기 때문에 발생하는 오류입니다.
* Visual Studio에서 프로젝트 우클릭한 다음 [속성] 클릭
* VC++ 디렉토리를 선택하고 포함 디렉터리에 다음 경로를 추가해줍니다.
```C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt```
* 10.0.14393.0 숫자는 컴퓨터마다 다를 수 있습니다.

**Comment by younghovpak** [comment]
### Windows SDK 버전을 찾을 수 없다는 오류
```
Windows SDK 버전 10.0.16299.0을(를) 찾을 수 없습니다. 필요한 버전의 Windows SDK를 설치하거나, 솔루션을 마우스 오른쪽 단추로 클릭하고 [솔루션 대상 변경]을 선택하거나 프로젝트 속성 페이지에서 SDK 버전을 변경하세요.```
* 위에 답변주신 내용대로 적용해서 stdio.h가 없다는 오류를 해결했는데 위와 같은 오류가 발생했습니다. 
* 이 오류에 대한 해결 방법을 알고 계시다면 답변주시면 감사하겠습니다.

**Comment by Haeeeun** [comment]
@younghovpak 
### Windows SDK 버전을 찾을 수 없다는 오류에 대한 해결 방법 #4
* 해당 오류는 Windows  SDK가 PC에 설치됐지만 Visual Studio에 적용이 안됐을 때 발생하는 오류입니다.
* 해결방법은 Visual Studio에서 프로젝트를 우클릭한 다음 [솔루션 대상 변경]을 클릭합니다.
* 아래 사진과 같이 Windows SDK 버전을 10.0.16299.0으로 변경하면 해결할 수 있습니다.
![1_2](https://user-images.githubusercontent.com/26876591/39912757-b6215ab8-553a-11e8-82c1-a4383bcc2da7.png)

**Comment by younghovpak** [comment]
@Haeeeun 해은씨 감사합니다! 위 내용대로 적용해서 오류를 해결하고 정상적으로 빌드 완료했습니다.
