### ISSUE TITLE
ScoreManagement print 예외 상황

### ISSUE THREAD

**Issue by younghovpak** [mingz17/OpenSW_Team2_StudentManagement#40]
### Context
* ScoreManagement에서 4번 print 했을 시에 sleep(20000) 걸어놓은 부분과 등록한 점수가 없을 때 Print 하면 이상한 평균값이 출력되는 문제가 있습니다. 해당 사항 수정해주시면 감사하겠습니다! @sssukho

**Comment by sssukho** [comment]
@younghovpak 확인했습니다 바로 수정하겠습니다.
