### ISSUE TITLE
과목을 등록하지 않은 상태에서 Course Modify 로 넘어갔을시 프로그램 정지

### ISSUE THREAD

**Issue by sssukho** [mingz17/OpenSW_Team2_StudentManagement#42]
### Context
* 메인 화면에서 과목을 등록하지 않고 바로 Modify로 넘어갈 수 있을 뿐만 아니라 아무 입력이나 두번 하면
바로 프로그램이 정지가 됩니다.

### Current Result
![image](https://user-images.githubusercontent.com/28735418/40373022-f51ec202-5e20-11e8-96c3-d99d69dea501.png)

### Expected result
* Course 구조체에 아무런 값들이 담겨져 있지 않은 경우에 Modify로 들어갈 수 없게 예외처리를 하면 될 것 같습니다.

**Comment by cj1ne** [comment]
예외사항을 고려를 못했었네요 :( 수정해서 pull request에 올리는대로 다시 코멘트 달겠습니다!

**Comment by cj1ne** [comment]
#46 Please join here. @sssukho
