### ISSUE TITLE
각자 맡은 기능별 참조해야할 기존 함수들 리스트가 필요해요!

### ISSUE THREAD

**Issue by sssukho** [mingz17/OpenSW_Team2_StudentManagement#5]
현재 각자 맡은 기능별로 헤더파일 하나, c파일 하나로 분리하고 있습니다.

이 과정에서 기존 프로그램이 돌아가는지도 한번 확인해보기 위해 각자 필요한 함수들을

제가 분리한 헤더파일 및 C파일에 넣어보고 컴파일 해보려고 하거든요!

각자 필요하신 기존 함수들 리스트 적어서 댓글로 달아주시기 바랍니다!

**Comment by Haeeeun** [comment]
저는 없습니다!

**Comment by younghovpak** [comment]
회의 결과 각자 맡은 기능별로 함수를 나누지 않기로 결론을 내려 해당 이슈를 닫겠습니다!
