### ISSUE TITLE
배열 초기화 문제

### ISSUE THREAD

**Issue by Haeeeun** [mingz17/OpenSW_Team2_StudentManagement#7]
배열이 어디까지 비어있는지 알기위해서 배열 선언할 때 배열을 null로 초기화하는 과정이 필요한거 같습니 다 이 문제에 대해 해결방법을 알고계신분은 알려주세요!

**Comment by cj1ne** [comment]
과목 구조체가 생성될 때마다 notice와 assignment의 배열을 ""으로 초기화하였습니다. 따라서 아무것도 입력되지 않은 요소는 strlen로 접근하시면 0이 출력될거에요!

지금 바로 develop 브랜치에 merge하겠습니다!

@younghovpak  @Haeeeun
