### ISSUE TITLE
과목 등록시 긴 문자 넣으면 뜨는 오류 

### ISSUE THREAD

**Issue by sssukho** [mingz17/OpenSW_Team2_StudentManagement#8]
제일 초기 화면에서 Computer Architectrue 라는 과목을 등록하였을 시(1번 메뉴 선택)

Run-Time Check Failure #2 - Stack around the variable 'courseName' was corrupted 오류가 뜹니다.

구글링 결과 긴 문자열을 입력받아 courseName 변수에 할당을 하면 사이즈가 넘어가서 그런듯 합니다!

오류 잡아주실 수 있나요?

**Comment by cj1ne** [comment]
네네 확인해보니까 제가 이름 배열의 크기를 20으로 설정해두었는데, Computer Architecture의 경우 null문자를 포함하면 22크기가 되네요. 영어로 설정하면 과목의 이름이 길어질 수 있는데 이점을 미처 생각하지 못한 것 같습니다 :(

넉넉하게 40정도로 수정할게요!
