### ISSUE TITLE
Develop branch bug

### ISSUE THREAD

**Issue by cj1ne** [mingz17/OpenSW_Team2_StudentManagement#9]
I checkout develop branch, and fetch & merge course branch. But, I caused SDK problem and couldn't include header file.

I saw the last writer of commit is @younghovpak, I think it caused by merge.

@Haeeeun @sssukho @mingz17 I can be only caused to me, can you check it?

**Comment by younghovpak** [comment]
제가 develop 브랜치에 올린 commit에 문제가 있었던 거 같습니다..
내용 다시 확인해보겠습니다!

**Comment by cj1ne** [comment]
@younghovpak  형 부분의 커밋을 삭제하고 정상 작동한 부분부터 먼저 병합하는건 어떨까요?
형님 자체적으로 문제가 해결되면, 그 때 병합하는게 좋을 것 같아요 !
